name: Test a module with CITGM

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module to test'
        required: true
      repository:
        description: 'CITGM repository to checkout'
        required: true
        default: nodejs/citgm
      ref:
        description: 'CITGM GitHub ref to checkout'
        required: true
        default: main

permissions:
  contents: read

jobs:
  show-parameters:
    name: Parameters for testing "${{ github.event.inputs.module }}"

    runs-on: ubuntu-latest

    steps:
      - name: Log workflow parameters
        env:
          WORKFLOW_PARAMETERS: ${{ toJSON(github.event.inputs) }}
        run: echo "$WORKFLOW_PARAMETERS"

  test-module:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 18.x
          - 20.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}
          show-progress: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install packages
        run: npm install

      - name: Run CITGM
        run: node bin/citgm.js ${{ github.event.inputs.module }}
